# Clusterlogs Notebook

In [1]:
import pandas as pd
from clusterlogs import pipeline, cluster_output

### 1. Download data from file and create pandas DataFrame with index 

In [12]:
df = pd.read_csv('test/error_messages.csv', index_col=0)

In [3]:
df = pd.read_csv('fts_mess_panda.csv', index_col=0).set_index('id')

In [13]:
df.head()

exeerrorcode                                       exeerrordiag  \
0             0      Error reading user generated output file list   
1             0      Error reading user generated output file list   
2            65  Non-zero return code from EVNTtoHITS (65); Log...   
3             0      Error reading user generated output file list   
4             0      Error reading user generated output file list   

      pandaid            starttime  
0  4496765923  2019-10-05T13:28:30  
1  4497204929  2019-10-06T03:31:42  
2  4496858944  2019-10-06T07:47:03  
3  4497111651  2019-10-05T21:09:37  
4  4496975592  2019-10-05T16:38:42

### 2. Initialize clusterization pipeline

In [14]:
target = 'exeerrordiag'

In [15]:
cluster = pipeline.ml_clustering(df, target, mode='create', model_name='test/word2vec_test.model')

### 3. Execute clusterization pipeline

In [16]:
cluster.process()

/Users/maria/anaconda3/lib/python3.7/site-packages/smart_open/smart_open_lib.py:398: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL


In [17]:
cluster.w2v_size

53

### 4. Get clusters statistics

In [18]:
output = cluster_output.Output(cluster.df, 
                               cluster.target, 
                               cluster.tokenizer, 
                               cluster.cluster_labels)

In [19]:
mode = 'INDEX'

In [20]:
output.clustered_output(mode)
stats = output.statistics(output_mode='frame')

In [21]:
stats.sort_values(by=['mean_similarity'])

cluster_name  cluster_size  \
35            35             9   
65            65             9   
112          112             2   
17            17             5   
41            41             3   
..           ...           ...   
58            58             9   
68            68             8   
54            54             8   
7              7             3   
149          149             1   

                                               pattern  mean_length  \
35   Input file argument T globbed to NO input file...       101.11   
65   Failed in data staging: Failed checking source...       178.67   
112  Non-zero return code from OMerge (*); Logfile ...        95.00   
17   Non-zero return code from AODtoDAOD (*); Logfi...       129.40   
41   File DAOD_D*.*._*.pool.root.* did not pass cor...        62.33   
..                                                 ...          ...   
58   Non-zero return code from AODtoDAOD (*); Logfi...       116.00   
68   Failed to clean up session dir before download...        56.00   
54   Fatal error in athena logfile: "Long ERROR mes...        97.00   
7    Non-zero return code from EVNTtoHITS (*); Logf...       195.00   
149  Non-zero return code from EVNTtoHITS (*); Logf...       103.00   

     mean_similarity  std_length  std_similarity  
35              0.90        3.60            0.03  
65              0.92        7.54            0.04  
112             0.94        2.00            0.00  
17              0.95        3.20            0.03  
41              0.95        0.94            0.01  
..               ...         ...             ...  
58              1.00        0.00            0.00  
68              1.00        0.00            0.00  
54              1.00        0.00            0.00  
7               1.00        0.00            0.00  
149             1.00        0.00            0.00  

[150 rows x 7 columns]

In [22]:
patterns = stats.sort_values(by='mean_similarity')[['pattern']].values

In [23]:
patterns

array([['Input file argument T globbed to NO input files - probably the file(s) are missing'],
       ['Failed in data staging: Failed checking source replica * Failed to obtain information about file: No such file or directory: Failed to stat file **/*/b_*.'],
       ['Non-zero return code from OMerge (*); Logfile error in log.OMerge: "KeyError: \'nentries\'"'],
       ['Non-zero return code from AODtoDAOD (*); Logfile error in log.AODtoDAOD: "* FATAL Standard std::exception is caught"'],
       ['File DAOD_D*.*._*.pool.root.* did not pass corruption test'],
       ['Non-zero return code from generate (*); Logfile error in log.generate: "*: MadSpin was run but can\'t find output folder Events/*_decayed_*."'],
       ['Non-zero return code from AODtoDAOD (*); Logfile error in log.AODtoDAOD: "* fault: Event counter: *; Run: *; Evt: *; Current algorithm: tag; Current Function: unknown"'],
       ['Non-zero return code from AODtoDAOD (*); Logfile error in log.AODtoDAOD: "StreamDAOD_* FATA

In [24]:
stats_1 = output.postprocessing()

In [25]:
stats_1

cluster_name  cluster_size  \
9            20          1821   
23           62          1141   
1            10           602   
6            13           427   
22           56           218   
20           53           116   
0             0           109   
12           28            97   
18            5            97   
14           31            84   
16           40            61   
15           33            36   
11           26            36   
19           50            30   
10           23            27   
7           147            18   
25           64            14   
21           55            11   
24           63            10   
26           65            10   
27           68             8   
2           101             7   
29           80             7   
13           30             4   
17           46             3   
8             2             2   
28           69             2   
5           120             1   
4           117             1   
3           111             1   

                                              pattern  mean_length  \
9                      Non-zero return code from  (*)       123.03   
23  Input file argument  globbed to NO input files...       100.04   
1   Missing AthenaMP outputs file * (probably athe...        60.31   
6   No events to process: * (skipEvents) >= * (inp...        62.00   
22                               LRMS error: (*) Job         28.89   
20  Fatal error in athena logfile: "Logfile error ...       146.87   
0       Error reading user generated output file list        45.00   
12                 AOD got a SIG signal (exit code *)        43.98   
18  Fatal error in athena logfile: "on at line * (...        91.49   
14                              Data type graph error        21.00   
16  Nonet code *); o at line * (see jobReport for ...       104.56   
15  Non-zero return code from AtoD (*); Logfile er...       169.11   
11                File * did not pass corruption test        58.19   
19  Fatal error in athena logfile: "Logfile error ...       209.00   
10             Eto got a SIGKILL signal (exit code *)        44.26   
7                                              : ****         6.00   
25                          Two identical output *: *        25.00   
21  Failed in data staging: Failed checking source...       115.00   
24  Event count check for EVNT to HITS failed: fou...       136.00   
26  Failed in data staging: ld en source replica *...       177.80   
27  Failed to clean up session dir before download...        56.00   
2   Failed in data staging: Failed to prepare dest...       197.43   
29  Non-zero return code from  (*); Logfile error ...       173.00   
13                     Non-zero return code from  (*)        36.75   
17  AODtoDAOD got a SIGBUS signal (exit code *); L...       216.00   
8                       Job submission to LRMS failed        29.00   
28  AODtoDAOD got a SIGKILL signal (exit code *); ...       134.50   
5   * got a SIGABRT signal (exit code *); Logfile ...        86.00   
4         generate got a SIGKILL signal (exit code *)        43.00   
3         Job was gone while performing data transfer        43.00   

    mean_similarity  std_length  std_similarity  
9              0.43       30.53            0.14  
23             0.90        0.37            0.00  
1              0.97        4.85            0.04  
6              0.98        0.00            0.00  
22             0.83        3.64            0.06  
20             0.63       10.41            0.05  
0              1.00        0.00            0.00  
12             0.95        0.14            0.04  
18             0.95        1.65            0.02  
14             1.00        0.00            0.00  
16             0.76        1.25            0.06  
15             0.95        3.77            0.03  
11             0.80        5.07            0.04  
19             1.00        0.00            0.00  
10             0.93        0.97            0.03  
7       

In [26]:
patterns1 = stats_1.sort_values(by='mean_similarity')[['pattern']].values

In [27]:
patterns1

array([['Non-zero return code from  (*)'],
       ['Non-zero return code from  (*); Logfile error in log.: "Eor: * u: *tretoOtion un'],
       ['Fatal error in athena logfile: "Logfile error in log.: "  e""'],
       ['AODtoDAOD got a SIGKILL signal (exit code *); Logfile error in log.AODtoDAOD: "* F tnrd oa"'],
       ['Failed in data staging: ld en source replica * ailed: No such file or directory: aid oat f'],
       ['Nonet code *); o at line * (see jobReport for further details)'],
       ['File * did not pass corruption test'],
       ['Failed in data staging: Failed to prepare destination * Failed to prepare destination: File exists: File requests have failed.: '],
       ['LRMS error: (*) Job '],
       ['Input file argument  globbed to NO input files - probably the file(s) are missing'],
       ['Non-zero return code from  (*)'],
       ['Eto got a SIGKILL signal (exit code *)'],
       ['Fatal error in athena logfile: "on at line * (see jobReport for further details)"'],
    

In [15]:
import difflib

In [16]:
sorted_df = output.stat_df.sort_values(by=['cluster_size'])[['cluster_size','cluster_name','pattern']]

In [135]:
sorted_df

cluster_size cluster_name  \
149             1          149   
138             1          138   
136             1          136   
139             1          139   
140             1          140   
..            ...          ...   
29            140           29   
13            385           13   
10            549           10   
20            805           20   
62           1098           62   

                                               pattern  
149  Non-zero return code from EVNTtoHITS (*); Logf...  
138  Non-zero return code from * (*); Logfile error...  
136  Non-zero return code from ESDtoAOD (*); Logfil...  
139  Non-zero return code from * (*); Logfile error...  
140  Non-zero return code from * (*); Logfile error...  
..                                                 ...  
29            Non-zero return code from EVNTtoHITS (*)  
13   No events to process: * (skipEvents) >= * (inp...  
10   Missing AthenaMP outputs file **r (probably at...  
20   Non-zero return code from AODtoDAOD (*); Logfi...  
62   Input file argument ${IN_MINBIAS_LOW/L} globbe...  

[150 rows x 3 columns]

In [136]:
def match(df, new_clusters):
    start = df.head(1)['pattern'].values[0]
#     print(start)
    ratio = [difflib.SequenceMatcher(None, start, x).ratio() for x in df['pattern']]
    df['ratio'] = ratio
    filtered = df[df['ratio'] > 0.6]['cluster_name'].values
    new_clusters.append(filtered)
#     print(filtered)
    df.drop(df[df['cluster_name'].isin(filtered)].index, inplace=True)
#     print(df)
    while df.shape[0] > 0:
        match(df, new_clusters)

In [137]:
new_clusters = []
# start = sorted_df.head(1)['pattern'].values[0]
# print(start)
match(sorted_df, new_clusters)

In [140]:
new_clusters

[array(['149', '136', '139', '133', '142', '143', '146', '144', '123',
        '105', '102', '51', '87', '79', '73', '72', '118', '112', '106',
        '48', '122', '109', '110', '108', '59', '90', '17', '3', '58',
        '93', '1', '36', '70', '39', '52', '74', '37', '24', '14', '45',
        '19'], dtype=object),
 array(['138', '97', '25', '86', '85', '9', '57'], dtype=object),
 array(['140'], dtype=object),
 array(['141', '117', '76', '67', '23', '28'], dtype=object),
 array(['135', '148', '30', '29'], dtype=object),
 array(['134', '81', '80'], dtype=object),
 array(['132', '95'], dtype=object),
 array(['131', '128', '91', '22'], dtype=object),
 array(['145', '137', '88'], dtype=object),
 array(['130', '84', '82', '101'], dtype=object),
 array(['129'], dtype=object),
 array(['127', '21', '99'], dtype=object),
 array(['126'], dtype=object),
 array(['124', '41', '8', '32', '26'], dtype=object),
 array(['107'], dtype=object),
 array(['120', '115', '69'], dtype=object),
 array(['121', 

In [145]:
a = []
for i in new_clusters:
    x = cluster.df[cluster.df['cluster'].isin(i)].index
    a.append({'cluster_name':i[-1],'idx':x})
print(a)

for i in a:
    cluster.df.loc[i['idx'], 'cluster_level_2'] = i['cluster_name']

[{'cluster_name': '19', 'idx': Int64Index([   2,    6,    7,    8,    9,   46,   59,   62,   63,   64,
            ...
            4861, 4874, 4875, 4897, 4912, 4915, 4937, 4949, 4956, 4967],
           dtype='int64', length=568)}, {'cluster_name': '57', 'idx': Int64Index([  50,   54,   55,  105,  275,  394,  580,  581,  645,  674,  914,
             923,  925,  926,  987,  993,  994, 1012, 1022, 1030, 1031, 1032,
            1037, 1246, 1268, 1343, 1389, 1555, 1843, 1845, 1863, 1944, 1948,
            1952, 1956, 1957, 1961, 2298, 2372, 2811, 2815, 2825, 2843, 2888,
            2913, 2915, 2926, 2932, 2933, 3022, 3251, 3524, 3572, 3763, 3772,
            3850, 3869, 3897, 3902, 3912, 4382, 4490, 4753, 4758, 4845, 4855,
            4883],
           dtype='int64')}, {'cluster_name': '140', 'idx': Int64Index([4037], dtype='int64')}, {'cluster_name': '28', 'idx': Int64Index([  90,  128,  260,  280,  290,  306,  408,  409,  410,  419,
            ...
            4374, 4390, 4403, 4405, 44

In [149]:
cluster.df['cluster_level_2'].describe()

count     5001
unique      43
top         62
freq      1141
Name: cluster_level_2, dtype: object

In [52]:
sorted_list = sorted_df['pattern'].tolist()

In [66]:
start = sorted_list[0]
print(start)
ratio = []
for x in sorted_list:
    ratio.append(difflib.SequenceMatcher(None, start, x).ratio())
print(ratio)
ids = [i for i,x in enumerate(ratio) if x > 0.6]
print(ids)

Non-zero return code from EVNTtoHITS (*); Logfile error in log.EVNTtoHITS: "StreamHITS FATAL * failed."
[1.0, 0.5638766519823789, 0.6181818181818182, 0.6272727272727273, 0.592057761732852, 0.1917808219178082, 0.44776119402985076, 0.4740740740740741, 0.6698113207547169, 0.6334841628959276, 0.32727272727272727, 0.4397163120567376, 0.6564102564102564, 0.3488372093023256, 0.39069767441860465, 0.2302158273381295, 0.5757575757575758, 0.3333333333333333, 0.5957446808510638, 0.6538461538461539, 0.17582417582417584, 0.15942028985507245, 0.663594470046083, 0.611353711790393, 0.5144927536231884, 0.5989304812834224, 0.455026455026455, 0.48, 0.2054794520547945, 0.5220588235294118, 0.39344262295081966, 0.5194805194805194, 0.273972602739726, 0.5886524822695035, 0.6255506607929515, 0.5841584158415841, 0.8682926829268293, 0.5517241379310345, 0.578397212543554, 0.5092250922509225, 0.784688995215311, 0.7159090909090909, 0.03289473684210526, 0.1793103448275862, 0.6666666666666666, 0.49122807017543857, 0.1

In [17]:
result = output.postprocessing()

In [19]:
result

matrix([[1.        , 0.18644068, 0.31446541, ..., 0.20979021, 0.19402985,
         0.1773399 ],
        [0.18644068, 1.        , 0.22564103, ..., 0.1452514 , 0.51973684,
         0.56903766],
        [0.33962264, 0.21538462, 1.        , ..., 0.23529412, 0.14977974,
         0.17283951],
        ...,
        [0.11188811, 0.16759777, 0.21568627, ..., 1.        , 0.14218009,
         0.20547945],
        [0.21641791, 0.53947368, 0.15859031, ..., 0.12322275, 1.        ,
         0.50922509],
        [0.1773399 , 0.56903766, 0.17283951, ..., 0.17808219, 0.50922509,
         1.        ]])

In [22]:
import numpy as np

In [27]:
threshold = 0.6
rows = np.where(result > threshold)

In [28]:
rows

(array([  0,   0,   0, ..., 149, 149, 149]),
 array([  0,  23,  51, ..., 139, 141, 149]))

In [20]:
similar

matrix([[1.        , 0.8159204 , 0.89010989, ..., 0.86829268, 0.62555066,
         1.        ]])

### Timings for all stages of clusterization pipeline

process - timing of all process

In [ ]:
cluster.timings

### Get all error messages in single cluster

In [ ]:
output.in_cluster(10)

In [ ]:
output.in_cluster(34)

### Output clusters - mode == 'ALL'  (for cluster '2')

In [ ]:
output.clustered_output(mode='ALL')['1']

### Output clusters - mode == 'INDEX' (for cluster '2')

In [ ]:
output.clustered_output(mode='INDEX')['1']

### Output clusters - mode == 'TARGET' (for cluster '2')

In [ ]:
output.clustered_output(mode='TARGET')['1']

### Output clusters - cluster labels

In [ ]:
cluster.cluster_labels

### Get epsilon value (which was used in DBSCAN algorithm)

In [ ]:
cluster.epsilon